//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenesWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajoDetalle
    {
        public int Id { get; set; }
        public Nullable<int> IdOrdenTrabajo { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    }
}
