//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenesWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroDetalle
    {
        public ParametroDetalle()
        {
            this.Articulo = new HashSet<Articulo>();
            this.ArticuloFormulaProduccion = new HashSet<ArticuloFormulaProduccion>();
            this.Movimiento = new HashSet<Movimiento>();
            this.OrdenTrabajo = new HashSet<OrdenTrabajo>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdPadre { get; set; }
    
        public virtual ICollection<Articulo> Articulo { get; set; }
        public virtual ICollection<ArticuloFormulaProduccion> ArticuloFormulaProduccion { get; set; }
        public virtual ICollection<Movimiento> Movimiento { get; set; }
        public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual Parametro Parametro { get; set; }
    }
}
