//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_ProduccionTest.WSOrdenTrabajos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSOrdenTrabajos.IOrdenTrabajos")]
    public interface IOrdenTrabajos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/crearOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/crearOrdResponse")]
        WS_Produccion.OrdenTrabajo crearOrd(WS_Produccion.OrdenTrabajo ordCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/crearOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/crearOrdResponse")]
        System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajo> crearOrdAsync(WS_Produccion.OrdenTrabajo ordCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/obtenerOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/obtenerOrdResponse")]
        WS_Produccion.OrdenTrabajo obtenerOrd(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/obtenerOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/obtenerOrdResponse")]
        System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajo> obtenerOrdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/modificarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/modificarOrdResponse")]
        WS_Produccion.OrdenTrabajo modificarOrd(WS_Produccion.OrdenTrabajo ordModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/modificarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/modificarOrdResponse")]
        System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajo> modificarOrdAsync(WS_Produccion.OrdenTrabajo ordModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/eliminarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/eliminarOrdResponse")]
        void eliminarOrd(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/eliminarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/eliminarOrdResponse")]
        System.Threading.Tasks.Task eliminarOrdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/listarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/listarOrdResponse")]
        WS_Produccion.OrdenTrabajo[] listarOrd(string idsEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/listarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/listarOrdResponse")]
        System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajo[]> listarOrdAsync(string idsEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/ListarLineaProduccion", ReplyAction="http://tempuri.org/IOrdenTrabajos/ListarLineaProduccionResponse")]
        WS_Produccion.MovimientoDetalle[] ListarLineaProduccion(int idOrdenTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/ListarLineaProduccion", ReplyAction="http://tempuri.org/IOrdenTrabajos/ListarLineaProduccionResponse")]
        System.Threading.Tasks.Task<WS_Produccion.MovimientoDetalle[]> ListarLineaProduccionAsync(int idOrdenTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/ListarMaterialesOrdenTrabajo", ReplyAction="http://tempuri.org/IOrdenTrabajos/ListarMaterialesOrdenTrabajoResponse")]
        WS_Produccion.MovimientoDetalle[] ListarMaterialesOrdenTrabajo(int idOrdenTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/ListarMaterialesOrdenTrabajo", ReplyAction="http://tempuri.org/IOrdenTrabajos/ListarMaterialesOrdenTrabajoResponse")]
        System.Threading.Tasks.Task<WS_Produccion.MovimientoDetalle[]> ListarMaterialesOrdenTrabajoAsync(int idOrdenTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/ModificarEstado", ReplyAction="http://tempuri.org/IOrdenTrabajos/ModificarEstadoResponse")]
        void ModificarEstado(int idOrdenTrabajo, int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/ModificarEstado", ReplyAction="http://tempuri.org/IOrdenTrabajos/ModificarEstadoResponse")]
        System.Threading.Tasks.Task ModificarEstadoAsync(int idOrdenTrabajo, int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/RegistrarOrdenTrabajoErronea", ReplyAction="http://tempuri.org/IOrdenTrabajos/RegistrarOrdenTrabajoErroneaResponse")]
        void RegistrarOrdenTrabajoErronea();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/RegistrarOrdenTrabajoErronea", ReplyAction="http://tempuri.org/IOrdenTrabajos/RegistrarOrdenTrabajoErroneaResponse")]
        System.Threading.Tasks.Task RegistrarOrdenTrabajoErroneaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdenTrabajosChannel : WS_ProduccionTest.WSOrdenTrabajos.IOrdenTrabajos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenTrabajosClient : System.ServiceModel.ClientBase<WS_ProduccionTest.WSOrdenTrabajos.IOrdenTrabajos>, WS_ProduccionTest.WSOrdenTrabajos.IOrdenTrabajos {
        
        public OrdenTrabajosClient() {
        }
        
        public OrdenTrabajosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenTrabajosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WS_Produccion.OrdenTrabajo crearOrd(WS_Produccion.OrdenTrabajo ordCrear) {
            return base.Channel.crearOrd(ordCrear);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajo> crearOrdAsync(WS_Produccion.OrdenTrabajo ordCrear) {
            return base.Channel.crearOrdAsync(ordCrear);
        }
        
        public WS_Produccion.OrdenTrabajo obtenerOrd(int id) {
            return base.Channel.obtenerOrd(id);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajo> obtenerOrdAsync(int id) {
            return base.Channel.obtenerOrdAsync(id);
        }
        
        public WS_Produccion.OrdenTrabajo modificarOrd(WS_Produccion.OrdenTrabajo ordModificar) {
            return base.Channel.modificarOrd(ordModificar);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajo> modificarOrdAsync(WS_Produccion.OrdenTrabajo ordModificar) {
            return base.Channel.modificarOrdAsync(ordModificar);
        }
        
        public void eliminarOrd(int id) {
            base.Channel.eliminarOrd(id);
        }
        
        public System.Threading.Tasks.Task eliminarOrdAsync(int id) {
            return base.Channel.eliminarOrdAsync(id);
        }
        
        public WS_Produccion.OrdenTrabajo[] listarOrd(string idsEstado) {
            return base.Channel.listarOrd(idsEstado);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajo[]> listarOrdAsync(string idsEstado) {
            return base.Channel.listarOrdAsync(idsEstado);
        }
        
        public WS_Produccion.MovimientoDetalle[] ListarLineaProduccion(int idOrdenTrabajo) {
            return base.Channel.ListarLineaProduccion(idOrdenTrabajo);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.MovimientoDetalle[]> ListarLineaProduccionAsync(int idOrdenTrabajo) {
            return base.Channel.ListarLineaProduccionAsync(idOrdenTrabajo);
        }
        
        public WS_Produccion.MovimientoDetalle[] ListarMaterialesOrdenTrabajo(int idOrdenTrabajo) {
            return base.Channel.ListarMaterialesOrdenTrabajo(idOrdenTrabajo);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.MovimientoDetalle[]> ListarMaterialesOrdenTrabajoAsync(int idOrdenTrabajo) {
            return base.Channel.ListarMaterialesOrdenTrabajoAsync(idOrdenTrabajo);
        }
        
        public void ModificarEstado(int idOrdenTrabajo, int idEstado) {
            base.Channel.ModificarEstado(idOrdenTrabajo, idEstado);
        }
        
        public System.Threading.Tasks.Task ModificarEstadoAsync(int idOrdenTrabajo, int idEstado) {
            return base.Channel.ModificarEstadoAsync(idOrdenTrabajo, idEstado);
        }
        
        public void RegistrarOrdenTrabajoErronea() {
            base.Channel.RegistrarOrdenTrabajoErronea();
        }
        
        public System.Threading.Tasks.Task RegistrarOrdenTrabajoErroneaAsync() {
            return base.Channel.RegistrarOrdenTrabajoErroneaAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSOrdenTrabajos.IOrdenTrabajoDetalle")]
    public interface IOrdenTrabajoDetalle {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/crearOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/crearOrdDetResponse")]
        void crearOrdDet(WS_Produccion.OrdenTrabajoDetalle ordDetCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/crearOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/crearOrdDetResponse")]
        System.Threading.Tasks.Task crearOrdDetAsync(WS_Produccion.OrdenTrabajoDetalle ordDetCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/obtenerOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/obtenerOrdDetResponse")]
        WS_Produccion.OrdenTrabajoDetalle obtenerOrdDet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/obtenerOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/obtenerOrdDetResponse")]
        System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajoDetalle> obtenerOrdDetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/modificarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/modificarOrdDetResponse")]
        void modificarOrdDet(WS_Produccion.OrdenTrabajoDetalle ordDetModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/modificarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/modificarOrdDetResponse")]
        System.Threading.Tasks.Task modificarOrdDetAsync(WS_Produccion.OrdenTrabajoDetalle ordDetModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/eliminarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/eliminarOrdDetResponse")]
        void eliminarOrdDet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/eliminarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/eliminarOrdDetResponse")]
        System.Threading.Tasks.Task eliminarOrdDetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/listarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/listarOrdDetResponse")]
        WS_Produccion.OrdenTrabajoDetalle[] listarOrdDet(int idOrdenTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/listarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/listarOrdDetResponse")]
        System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajoDetalle[]> listarOrdDetAsync(int idOrdenTrabajo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdenTrabajoDetalleChannel : WS_ProduccionTest.WSOrdenTrabajos.IOrdenTrabajoDetalle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenTrabajoDetalleClient : System.ServiceModel.ClientBase<WS_ProduccionTest.WSOrdenTrabajos.IOrdenTrabajoDetalle>, WS_ProduccionTest.WSOrdenTrabajos.IOrdenTrabajoDetalle {
        
        public OrdenTrabajoDetalleClient() {
        }
        
        public OrdenTrabajoDetalleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenTrabajoDetalleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajoDetalleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajoDetalleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void crearOrdDet(WS_Produccion.OrdenTrabajoDetalle ordDetCrear) {
            base.Channel.crearOrdDet(ordDetCrear);
        }
        
        public System.Threading.Tasks.Task crearOrdDetAsync(WS_Produccion.OrdenTrabajoDetalle ordDetCrear) {
            return base.Channel.crearOrdDetAsync(ordDetCrear);
        }
        
        public WS_Produccion.OrdenTrabajoDetalle obtenerOrdDet(int id) {
            return base.Channel.obtenerOrdDet(id);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajoDetalle> obtenerOrdDetAsync(int id) {
            return base.Channel.obtenerOrdDetAsync(id);
        }
        
        public void modificarOrdDet(WS_Produccion.OrdenTrabajoDetalle ordDetModificar) {
            base.Channel.modificarOrdDet(ordDetModificar);
        }
        
        public System.Threading.Tasks.Task modificarOrdDetAsync(WS_Produccion.OrdenTrabajoDetalle ordDetModificar) {
            return base.Channel.modificarOrdDetAsync(ordDetModificar);
        }
        
        public void eliminarOrdDet(int id) {
            base.Channel.eliminarOrdDet(id);
        }
        
        public System.Threading.Tasks.Task eliminarOrdDetAsync(int id) {
            return base.Channel.eliminarOrdDetAsync(id);
        }
        
        public WS_Produccion.OrdenTrabajoDetalle[] listarOrdDet(int idOrdenTrabajo) {
            return base.Channel.listarOrdDet(idOrdenTrabajo);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajoDetalle[]> listarOrdDetAsync(int idOrdenTrabajo) {
            return base.Channel.listarOrdDetAsync(idOrdenTrabajo);
        }
    }
}
