//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo1.WSReportes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSReportes.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/obtenerOrden", ReplyAction="http://tempuri.org/IReportService/obtenerOrdenResponse")]
        WS_Produccion.OrdenTrabajo obtenerOrden(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/obtenerOrden", ReplyAction="http://tempuri.org/IReportService/obtenerOrdenResponse")]
        System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajo> obtenerOrdenAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ListarEficiencia", ReplyAction="http://tempuri.org/IReportService/ListarEficienciaResponse")]
        WS_Produccion.OrdenTrabajo[] ListarEficiencia(string fechaInicial, string fechFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ListarEficiencia", ReplyAction="http://tempuri.org/IReportService/ListarEficienciaResponse")]
        System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajo[]> ListarEficienciaAsync(string fechaInicial, string fechFinal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : Prototipo1.WSReportes.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<Prototipo1.WSReportes.IReportService>, Prototipo1.WSReportes.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WS_Produccion.OrdenTrabajo obtenerOrden(int id) {
            return base.Channel.obtenerOrden(id);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajo> obtenerOrdenAsync(int id) {
            return base.Channel.obtenerOrdenAsync(id);
        }
        
        public WS_Produccion.OrdenTrabajo[] ListarEficiencia(string fechaInicial, string fechFinal) {
            return base.Channel.ListarEficiencia(fechaInicial, fechFinal);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.OrdenTrabajo[]> ListarEficienciaAsync(string fechaInicial, string fechFinal) {
            return base.Channel.ListarEficienciaAsync(fechaInicial, fechFinal);
        }
    }
}
