//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_ProduccionTest.GesMovWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimiento", Namespace="http://schemas.datacontract.org/2004/07/WS_Produccion")]
    [System.SerializableAttribute()]
    public partial class Movimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlmacenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdAlmacenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdOrdenTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS_ProduccionTest.GesMovWS.MovimientoDetalle[] ListaMovimientoDetallesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoMovimientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Almacen {
            get {
                return this.AlmacenField;
            }
            set {
                if ((object.ReferenceEquals(this.AlmacenField, value) != true)) {
                    this.AlmacenField = value;
                    this.RaisePropertyChanged("Almacen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdAlmacen {
            get {
                return this.IdAlmacenField;
            }
            set {
                if ((this.IdAlmacenField.Equals(value) != true)) {
                    this.IdAlmacenField = value;
                    this.RaisePropertyChanged("IdAlmacen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdOrdenTrabajo {
            get {
                return this.IdOrdenTrabajoField;
            }
            set {
                if ((this.IdOrdenTrabajoField.Equals(value) != true)) {
                    this.IdOrdenTrabajoField = value;
                    this.RaisePropertyChanged("IdOrdenTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WS_ProduccionTest.GesMovWS.MovimientoDetalle[] ListaMovimientoDetalles {
            get {
                return this.ListaMovimientoDetallesField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaMovimientoDetallesField, value) != true)) {
                    this.ListaMovimientoDetallesField = value;
                    this.RaisePropertyChanged("ListaMovimientoDetalles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMovimiento {
            get {
                return this.TipoMovimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoMovimientoField, value) != true)) {
                    this.TipoMovimientoField = value;
                    this.RaisePropertyChanged("TipoMovimiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimientoDetalle", Namespace="http://schemas.datacontract.org/2004/07/WS_Produccion")]
    [System.SerializableAttribute()]
    public partial class MovimientoDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> StockActualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Articulo {
            get {
                return this.ArticuloField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticuloField, value) != true)) {
                    this.ArticuloField = value;
                    this.RaisePropertyChanged("Articulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdArticulo {
            get {
                return this.IdArticuloField;
            }
            set {
                if ((this.IdArticuloField.Equals(value) != true)) {
                    this.IdArticuloField = value;
                    this.RaisePropertyChanged("IdArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMovimiento {
            get {
                return this.IdMovimientoField;
            }
            set {
                if ((this.IdMovimientoField.Equals(value) != true)) {
                    this.IdMovimientoField = value;
                    this.RaisePropertyChanged("IdMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StockActual {
            get {
                return this.StockActualField;
            }
            set {
                if ((this.StockActualField.Equals(value) != true)) {
                    this.StockActualField = value;
                    this.RaisePropertyChanged("StockActual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Errores", Namespace="http://schemas.datacontract.org/2004/07/WS_Produccion.Excepciones")]
    [System.SerializableAttribute()]
    public partial class Errores : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod {
            get {
                return this.codField;
            }
            set {
                if ((object.ReferenceEquals(this.codField, value) != true)) {
                    this.codField = value;
                    this.RaisePropertyChanged("cod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string des {
            get {
                return this.desField;
            }
            set {
                if ((object.ReferenceEquals(this.desField, value) != true)) {
                    this.desField = value;
                    this.RaisePropertyChanged("des");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GesMovWS.IGestionarMovimiento")]
    public interface IGestionarMovimiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarMovimiento/CrearMov", ReplyAction="http://tempuri.org/IGestionarMovimiento/CrearMovResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WS_ProduccionTest.GesMovWS.Errores), Action="http://tempuri.org/IGestionarMovimiento/CrearMovErroresFault", Name="Errores", Namespace="http://schemas.datacontract.org/2004/07/WS_Produccion.Excepciones")]
        WS_ProduccionTest.GesMovWS.Movimiento CrearMov(WS_ProduccionTest.GesMovWS.Movimiento movCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarMovimiento/CrearMov", ReplyAction="http://tempuri.org/IGestionarMovimiento/CrearMovResponse")]
        System.Threading.Tasks.Task<WS_ProduccionTest.GesMovWS.Movimiento> CrearMovAsync(WS_ProduccionTest.GesMovWS.Movimiento movCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarMovimiento/obtenerMov", ReplyAction="http://tempuri.org/IGestionarMovimiento/obtenerMovResponse")]
        WS_ProduccionTest.GesMovWS.Movimiento obtenerMov(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarMovimiento/obtenerMov", ReplyAction="http://tempuri.org/IGestionarMovimiento/obtenerMovResponse")]
        System.Threading.Tasks.Task<WS_ProduccionTest.GesMovWS.Movimiento> obtenerMovAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarMovimiento/grabarMov", ReplyAction="http://tempuri.org/IGestionarMovimiento/grabarMovResponse")]
        WS_ProduccionTest.GesMovWS.Movimiento grabarMov(WS_ProduccionTest.GesMovWS.Movimiento movGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarMovimiento/grabarMov", ReplyAction="http://tempuri.org/IGestionarMovimiento/grabarMovResponse")]
        System.Threading.Tasks.Task<WS_ProduccionTest.GesMovWS.Movimiento> grabarMovAsync(WS_ProduccionTest.GesMovWS.Movimiento movGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarMovimiento/borrarMov", ReplyAction="http://tempuri.org/IGestionarMovimiento/borrarMovResponse")]
        void borrarMov(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarMovimiento/borrarMov", ReplyAction="http://tempuri.org/IGestionarMovimiento/borrarMovResponse")]
        System.Threading.Tasks.Task borrarMovAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarMovimiento/listarMov", ReplyAction="http://tempuri.org/IGestionarMovimiento/listarMovResponse")]
        WS_ProduccionTest.GesMovWS.Movimiento[] listarMov(string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarMovimiento/listarMov", ReplyAction="http://tempuri.org/IGestionarMovimiento/listarMovResponse")]
        System.Threading.Tasks.Task<WS_ProduccionTest.GesMovWS.Movimiento[]> listarMovAsync(string tipo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionarMovimientoChannel : WS_ProduccionTest.GesMovWS.IGestionarMovimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionarMovimientoClient : System.ServiceModel.ClientBase<WS_ProduccionTest.GesMovWS.IGestionarMovimiento>, WS_ProduccionTest.GesMovWS.IGestionarMovimiento {
        
        public GestionarMovimientoClient() {
        }
        
        public GestionarMovimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionarMovimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionarMovimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionarMovimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WS_ProduccionTest.GesMovWS.Movimiento CrearMov(WS_ProduccionTest.GesMovWS.Movimiento movCrear) {
            return base.Channel.CrearMov(movCrear);
        }
        
        public System.Threading.Tasks.Task<WS_ProduccionTest.GesMovWS.Movimiento> CrearMovAsync(WS_ProduccionTest.GesMovWS.Movimiento movCrear) {
            return base.Channel.CrearMovAsync(movCrear);
        }
        
        public WS_ProduccionTest.GesMovWS.Movimiento obtenerMov(string id) {
            return base.Channel.obtenerMov(id);
        }
        
        public System.Threading.Tasks.Task<WS_ProduccionTest.GesMovWS.Movimiento> obtenerMovAsync(string id) {
            return base.Channel.obtenerMovAsync(id);
        }
        
        public WS_ProduccionTest.GesMovWS.Movimiento grabarMov(WS_ProduccionTest.GesMovWS.Movimiento movGrabar) {
            return base.Channel.grabarMov(movGrabar);
        }
        
        public System.Threading.Tasks.Task<WS_ProduccionTest.GesMovWS.Movimiento> grabarMovAsync(WS_ProduccionTest.GesMovWS.Movimiento movGrabar) {
            return base.Channel.grabarMovAsync(movGrabar);
        }
        
        public void borrarMov(string id) {
            base.Channel.borrarMov(id);
        }
        
        public System.Threading.Tasks.Task borrarMovAsync(string id) {
            return base.Channel.borrarMovAsync(id);
        }
        
        public WS_ProduccionTest.GesMovWS.Movimiento[] listarMov(string tipo) {
            return base.Channel.listarMov(tipo);
        }
        
        public System.Threading.Tasks.Task<WS_ProduccionTest.GesMovWS.Movimiento[]> listarMovAsync(string tipo) {
            return base.Channel.listarMovAsync(tipo);
        }
    }
}
