//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo1.WSArticulos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSArticulos.IArticulos")]
    public interface IArticulos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/Modificar", ReplyAction="http://tempuri.org/IArticulos/ModificarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WS_Produccion.Excepciones.SinStockExceptions), Action="http://tempuri.org/IArticulos/ModificarSinStockExceptionsFault", Name="SinStockExceptions", Namespace="http://schemas.datacontract.org/2004/07/WS_Produccion.Excepciones")]
        WS_Produccion.Articulo Modificar(WS_Produccion.Articulo ArticuloAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/Modificar", ReplyAction="http://tempuri.org/IArticulos/ModificarResponse")]
        System.Threading.Tasks.Task<WS_Produccion.Articulo> ModificarAsync(WS_Produccion.Articulo ArticuloAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/Obtener", ReplyAction="http://tempuri.org/IArticulos/ObtenerResponse")]
        WS_Produccion.Articulo Obtener(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/Obtener", ReplyAction="http://tempuri.org/IArticulos/ObtenerResponse")]
        System.Threading.Tasks.Task<WS_Produccion.Articulo> ObtenerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/ListarArticulos", ReplyAction="http://tempuri.org/IArticulos/ListarArticulosResponse")]
        WS_Produccion.Articulo[] ListarArticulos(string tipoExistencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticulos/ListarArticulos", ReplyAction="http://tempuri.org/IArticulos/ListarArticulosResponse")]
        System.Threading.Tasks.Task<WS_Produccion.Articulo[]> ListarArticulosAsync(string tipoExistencia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArticulosChannel : Prototipo1.WSArticulos.IArticulos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArticulosClient : System.ServiceModel.ClientBase<Prototipo1.WSArticulos.IArticulos>, Prototipo1.WSArticulos.IArticulos {
        
        public ArticulosClient() {
        }
        
        public ArticulosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArticulosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticulosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticulosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WS_Produccion.Articulo Modificar(WS_Produccion.Articulo ArticuloAModificar) {
            return base.Channel.Modificar(ArticuloAModificar);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.Articulo> ModificarAsync(WS_Produccion.Articulo ArticuloAModificar) {
            return base.Channel.ModificarAsync(ArticuloAModificar);
        }
        
        public WS_Produccion.Articulo Obtener(int id) {
            return base.Channel.Obtener(id);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.Articulo> ObtenerAsync(int id) {
            return base.Channel.ObtenerAsync(id);
        }
        
        public WS_Produccion.Articulo[] ListarArticulos(string tipoExistencia) {
            return base.Channel.ListarArticulos(tipoExistencia);
        }
        
        public System.Threading.Tasks.Task<WS_Produccion.Articulo[]> ListarArticulosAsync(string tipoExistencia) {
            return base.Channel.ListarArticulosAsync(tipoExistencia);
        }
    }
}
