//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_ProduccionTest.OrdWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenTrabajo", Namespace="http://schemas.datacontract.org/2004/07/WS_Produccion")]
    [System.SerializableAttribute()]
    public partial class OrdenTrabajo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle[] ListaDetalleOrdenTrabajoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle[] ListaDetalleOrdenTrabajo {
            get {
                return this.ListaDetalleOrdenTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaDetalleOrdenTrabajoField, value) != true)) {
                    this.ListaDetalleOrdenTrabajoField = value;
                    this.RaisePropertyChanged("ListaDetalleOrdenTrabajo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenTrabajoDetalle", Namespace="http://schemas.datacontract.org/2004/07/WS_Produccion")]
    [System.SerializableAttribute()]
    public partial class OrdenTrabajoDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdOrdenTrabajoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Articulo {
            get {
                return this.ArticuloField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticuloField, value) != true)) {
                    this.ArticuloField = value;
                    this.RaisePropertyChanged("Articulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArticulo {
            get {
                return this.IdArticuloField;
            }
            set {
                if ((this.IdArticuloField.Equals(value) != true)) {
                    this.IdArticuloField = value;
                    this.RaisePropertyChanged("IdArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOrdenTrabajo {
            get {
                return this.IdOrdenTrabajoField;
            }
            set {
                if ((this.IdOrdenTrabajoField.Equals(value) != true)) {
                    this.IdOrdenTrabajoField = value;
                    this.RaisePropertyChanged("IdOrdenTrabajo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimientoDetalle", Namespace="http://schemas.datacontract.org/2004/07/WS_Produccion")]
    [System.SerializableAttribute()]
    public partial class MovimientoDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> StockActualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Articulo {
            get {
                return this.ArticuloField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticuloField, value) != true)) {
                    this.ArticuloField = value;
                    this.RaisePropertyChanged("Articulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdArticulo {
            get {
                return this.IdArticuloField;
            }
            set {
                if ((this.IdArticuloField.Equals(value) != true)) {
                    this.IdArticuloField = value;
                    this.RaisePropertyChanged("IdArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMovimiento {
            get {
                return this.IdMovimientoField;
            }
            set {
                if ((this.IdMovimientoField.Equals(value) != true)) {
                    this.IdMovimientoField = value;
                    this.RaisePropertyChanged("IdMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StockActual {
            get {
                return this.StockActualField;
            }
            set {
                if ((this.StockActualField.Equals(value) != true)) {
                    this.StockActualField = value;
                    this.RaisePropertyChanged("StockActual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrdWS.IOrdenTrabajos")]
    public interface IOrdenTrabajos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/crearOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/crearOrdResponse")]
        WS_ProduccionTest.OrdWS.OrdenTrabajo crearOrd(WS_ProduccionTest.OrdWS.OrdenTrabajo ordCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/crearOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/crearOrdResponse")]
        System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.OrdenTrabajo> crearOrdAsync(WS_ProduccionTest.OrdWS.OrdenTrabajo ordCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/obtenerOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/obtenerOrdResponse")]
        WS_ProduccionTest.OrdWS.OrdenTrabajo obtenerOrd(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/obtenerOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/obtenerOrdResponse")]
        System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.OrdenTrabajo> obtenerOrdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/modificarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/modificarOrdResponse")]
        WS_ProduccionTest.OrdWS.OrdenTrabajo modificarOrd(WS_ProduccionTest.OrdWS.OrdenTrabajo ordModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/modificarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/modificarOrdResponse")]
        System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.OrdenTrabajo> modificarOrdAsync(WS_ProduccionTest.OrdWS.OrdenTrabajo ordModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/eliminarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/eliminarOrdResponse")]
        void eliminarOrd(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/eliminarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/eliminarOrdResponse")]
        System.Threading.Tasks.Task eliminarOrdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/listarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/listarOrdResponse")]
        WS_ProduccionTest.OrdWS.OrdenTrabajo[] listarOrd(string idsEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/listarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/listarOrdResponse")]
        System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.OrdenTrabajo[]> listarOrdAsync(string idsEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/ListarLineaProduccion", ReplyAction="http://tempuri.org/IOrdenTrabajos/ListarLineaProduccionResponse")]
        WS_ProduccionTest.OrdWS.MovimientoDetalle[] ListarLineaProduccion(int idOrdenTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/ListarLineaProduccion", ReplyAction="http://tempuri.org/IOrdenTrabajos/ListarLineaProduccionResponse")]
        System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.MovimientoDetalle[]> ListarLineaProduccionAsync(int idOrdenTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/ListarMaterialesOrdenTrabajo", ReplyAction="http://tempuri.org/IOrdenTrabajos/ListarMaterialesOrdenTrabajoResponse")]
        WS_ProduccionTest.OrdWS.MovimientoDetalle[] ListarMaterialesOrdenTrabajo(int idOrdenTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/ListarMaterialesOrdenTrabajo", ReplyAction="http://tempuri.org/IOrdenTrabajos/ListarMaterialesOrdenTrabajoResponse")]
        System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.MovimientoDetalle[]> ListarMaterialesOrdenTrabajoAsync(int idOrdenTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/ModificarEstado", ReplyAction="http://tempuri.org/IOrdenTrabajos/ModificarEstadoResponse")]
        void ModificarEstado(int idOrdenTrabajo, int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/ModificarEstado", ReplyAction="http://tempuri.org/IOrdenTrabajos/ModificarEstadoResponse")]
        System.Threading.Tasks.Task ModificarEstadoAsync(int idOrdenTrabajo, int idEstado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdenTrabajosChannel : WS_ProduccionTest.OrdWS.IOrdenTrabajos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenTrabajosClient : System.ServiceModel.ClientBase<WS_ProduccionTest.OrdWS.IOrdenTrabajos>, WS_ProduccionTest.OrdWS.IOrdenTrabajos {
        
        public OrdenTrabajosClient() {
        }
        
        public OrdenTrabajosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenTrabajosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WS_ProduccionTest.OrdWS.OrdenTrabajo crearOrd(WS_ProduccionTest.OrdWS.OrdenTrabajo ordCrear) {
            return base.Channel.crearOrd(ordCrear);
        }
        
        public System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.OrdenTrabajo> crearOrdAsync(WS_ProduccionTest.OrdWS.OrdenTrabajo ordCrear) {
            return base.Channel.crearOrdAsync(ordCrear);
        }
        
        public WS_ProduccionTest.OrdWS.OrdenTrabajo obtenerOrd(int id) {
            return base.Channel.obtenerOrd(id);
        }
        
        public System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.OrdenTrabajo> obtenerOrdAsync(int id) {
            return base.Channel.obtenerOrdAsync(id);
        }
        
        public WS_ProduccionTest.OrdWS.OrdenTrabajo modificarOrd(WS_ProduccionTest.OrdWS.OrdenTrabajo ordModificar) {
            return base.Channel.modificarOrd(ordModificar);
        }
        
        public System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.OrdenTrabajo> modificarOrdAsync(WS_ProduccionTest.OrdWS.OrdenTrabajo ordModificar) {
            return base.Channel.modificarOrdAsync(ordModificar);
        }
        
        public void eliminarOrd(int id) {
            base.Channel.eliminarOrd(id);
        }
        
        public System.Threading.Tasks.Task eliminarOrdAsync(int id) {
            return base.Channel.eliminarOrdAsync(id);
        }
        
        public WS_ProduccionTest.OrdWS.OrdenTrabajo[] listarOrd(string idsEstado) {
            return base.Channel.listarOrd(idsEstado);
        }
        
        public System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.OrdenTrabajo[]> listarOrdAsync(string idsEstado) {
            return base.Channel.listarOrdAsync(idsEstado);
        }
        
        public WS_ProduccionTest.OrdWS.MovimientoDetalle[] ListarLineaProduccion(int idOrdenTrabajo) {
            return base.Channel.ListarLineaProduccion(idOrdenTrabajo);
        }
        
        public System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.MovimientoDetalle[]> ListarLineaProduccionAsync(int idOrdenTrabajo) {
            return base.Channel.ListarLineaProduccionAsync(idOrdenTrabajo);
        }
        
        public WS_ProduccionTest.OrdWS.MovimientoDetalle[] ListarMaterialesOrdenTrabajo(int idOrdenTrabajo) {
            return base.Channel.ListarMaterialesOrdenTrabajo(idOrdenTrabajo);
        }
        
        public System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.MovimientoDetalle[]> ListarMaterialesOrdenTrabajoAsync(int idOrdenTrabajo) {
            return base.Channel.ListarMaterialesOrdenTrabajoAsync(idOrdenTrabajo);
        }
        
        public void ModificarEstado(int idOrdenTrabajo, int idEstado) {
            base.Channel.ModificarEstado(idOrdenTrabajo, idEstado);
        }
        
        public System.Threading.Tasks.Task ModificarEstadoAsync(int idOrdenTrabajo, int idEstado) {
            return base.Channel.ModificarEstadoAsync(idOrdenTrabajo, idEstado);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrdWS.IOrdenTrabajoDetalle")]
    public interface IOrdenTrabajoDetalle {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/crearOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/crearOrdDetResponse")]
        void crearOrdDet(WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle ordDetCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/crearOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/crearOrdDetResponse")]
        System.Threading.Tasks.Task crearOrdDetAsync(WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle ordDetCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/obtenerOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/obtenerOrdDetResponse")]
        WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle obtenerOrdDet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/obtenerOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/obtenerOrdDetResponse")]
        System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle> obtenerOrdDetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/modificarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/modificarOrdDetResponse")]
        void modificarOrdDet(WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle ordDetModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/modificarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/modificarOrdDetResponse")]
        System.Threading.Tasks.Task modificarOrdDetAsync(WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle ordDetModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/eliminarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/eliminarOrdDetResponse")]
        void eliminarOrdDet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/eliminarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/eliminarOrdDetResponse")]
        System.Threading.Tasks.Task eliminarOrdDetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/listarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/listarOrdDetResponse")]
        WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle[] listarOrdDet(int idOrdenTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/listarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/listarOrdDetResponse")]
        System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle[]> listarOrdDetAsync(int idOrdenTrabajo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdenTrabajoDetalleChannel : WS_ProduccionTest.OrdWS.IOrdenTrabajoDetalle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenTrabajoDetalleClient : System.ServiceModel.ClientBase<WS_ProduccionTest.OrdWS.IOrdenTrabajoDetalle>, WS_ProduccionTest.OrdWS.IOrdenTrabajoDetalle {
        
        public OrdenTrabajoDetalleClient() {
        }
        
        public OrdenTrabajoDetalleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenTrabajoDetalleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajoDetalleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajoDetalleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void crearOrdDet(WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle ordDetCrear) {
            base.Channel.crearOrdDet(ordDetCrear);
        }
        
        public System.Threading.Tasks.Task crearOrdDetAsync(WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle ordDetCrear) {
            return base.Channel.crearOrdDetAsync(ordDetCrear);
        }
        
        public WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle obtenerOrdDet(int id) {
            return base.Channel.obtenerOrdDet(id);
        }
        
        public System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle> obtenerOrdDetAsync(int id) {
            return base.Channel.obtenerOrdDetAsync(id);
        }
        
        public void modificarOrdDet(WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle ordDetModificar) {
            base.Channel.modificarOrdDet(ordDetModificar);
        }
        
        public System.Threading.Tasks.Task modificarOrdDetAsync(WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle ordDetModificar) {
            return base.Channel.modificarOrdDetAsync(ordDetModificar);
        }
        
        public void eliminarOrdDet(int id) {
            base.Channel.eliminarOrdDet(id);
        }
        
        public System.Threading.Tasks.Task eliminarOrdDetAsync(int id) {
            return base.Channel.eliminarOrdDetAsync(id);
        }
        
        public WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle[] listarOrdDet(int idOrdenTrabajo) {
            return base.Channel.listarOrdDet(idOrdenTrabajo);
        }
        
        public System.Threading.Tasks.Task<WS_ProduccionTest.OrdWS.OrdenTrabajoDetalle[]> listarOrdDetAsync(int idOrdenTrabajo) {
            return base.Channel.listarOrdDetAsync(idOrdenTrabajo);
        }
    }
}
