//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo1.WSord {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenTrabajo", Namespace="http://schemas.datacontract.org/2004/07/WS_Produccion")]
    [System.SerializableAttribute()]
    public partial class OrdenTrabajo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenTrabajoDetalle", Namespace="http://schemas.datacontract.org/2004/07/WS_Produccion")]
    [System.SerializableAttribute()]
    public partial class OrdenTrabajoDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdOrdenTrabajoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArticulo {
            get {
                return this.IdArticuloField;
            }
            set {
                if ((this.IdArticuloField.Equals(value) != true)) {
                    this.IdArticuloField = value;
                    this.RaisePropertyChanged("IdArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOrdenTrabajo {
            get {
                return this.IdOrdenTrabajoField;
            }
            set {
                if ((this.IdOrdenTrabajoField.Equals(value) != true)) {
                    this.IdOrdenTrabajoField = value;
                    this.RaisePropertyChanged("IdOrdenTrabajo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSord.IOrdenTrabajos")]
    public interface IOrdenTrabajos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/crearOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/crearOrdResponse")]
        Prototipo1.WSord.OrdenTrabajo crearOrd(Prototipo1.WSord.OrdenTrabajo ordCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/crearOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/crearOrdResponse")]
        System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajo> crearOrdAsync(Prototipo1.WSord.OrdenTrabajo ordCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/obtenerOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/obtenerOrdResponse")]
        Prototipo1.WSord.OrdenTrabajo obtenerOrd(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/obtenerOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/obtenerOrdResponse")]
        System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajo> obtenerOrdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/modificarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/modificarOrdResponse")]
        Prototipo1.WSord.OrdenTrabajo modificarOrd(Prototipo1.WSord.OrdenTrabajo ordModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/modificarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/modificarOrdResponse")]
        System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajo> modificarOrdAsync(Prototipo1.WSord.OrdenTrabajo ordModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/eliminarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/eliminarOrdResponse")]
        void eliminarOrd(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/eliminarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/eliminarOrdResponse")]
        System.Threading.Tasks.Task eliminarOrdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/listarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/listarOrdResponse")]
        Prototipo1.WSord.OrdenTrabajo[] listarOrd();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajos/listarOrd", ReplyAction="http://tempuri.org/IOrdenTrabajos/listarOrdResponse")]
        System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajo[]> listarOrdAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdenTrabajosChannel : Prototipo1.WSord.IOrdenTrabajos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenTrabajosClient : System.ServiceModel.ClientBase<Prototipo1.WSord.IOrdenTrabajos>, Prototipo1.WSord.IOrdenTrabajos {
        
        public OrdenTrabajosClient() {
        }
        
        public OrdenTrabajosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenTrabajosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Prototipo1.WSord.OrdenTrabajo crearOrd(Prototipo1.WSord.OrdenTrabajo ordCrear) {
            return base.Channel.crearOrd(ordCrear);
        }
        
        public System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajo> crearOrdAsync(Prototipo1.WSord.OrdenTrabajo ordCrear) {
            return base.Channel.crearOrdAsync(ordCrear);
        }
        
        public Prototipo1.WSord.OrdenTrabajo obtenerOrd(int id) {
            return base.Channel.obtenerOrd(id);
        }
        
        public System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajo> obtenerOrdAsync(int id) {
            return base.Channel.obtenerOrdAsync(id);
        }
        
        public Prototipo1.WSord.OrdenTrabajo modificarOrd(Prototipo1.WSord.OrdenTrabajo ordModificar) {
            return base.Channel.modificarOrd(ordModificar);
        }
        
        public System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajo> modificarOrdAsync(Prototipo1.WSord.OrdenTrabajo ordModificar) {
            return base.Channel.modificarOrdAsync(ordModificar);
        }
        
        public void eliminarOrd(int id) {
            base.Channel.eliminarOrd(id);
        }
        
        public System.Threading.Tasks.Task eliminarOrdAsync(int id) {
            return base.Channel.eliminarOrdAsync(id);
        }
        
        public Prototipo1.WSord.OrdenTrabajo[] listarOrd() {
            return base.Channel.listarOrd();
        }
        
        public System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajo[]> listarOrdAsync() {
            return base.Channel.listarOrdAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSord.IOrdenTrabajoDetalle")]
    public interface IOrdenTrabajoDetalle {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/crearOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/crearOrdDetResponse")]
        Prototipo1.WSord.OrdenTrabajoDetalle crearOrdDet(Prototipo1.WSord.OrdenTrabajoDetalle ordDetCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/crearOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/crearOrdDetResponse")]
        System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajoDetalle> crearOrdDetAsync(Prototipo1.WSord.OrdenTrabajoDetalle ordDetCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/obtenerOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/obtenerOrdDetResponse")]
        Prototipo1.WSord.OrdenTrabajoDetalle obtenerOrdDet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/obtenerOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/obtenerOrdDetResponse")]
        System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajoDetalle> obtenerOrdDetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/modificarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/modificarOrdDetResponse")]
        Prototipo1.WSord.OrdenTrabajoDetalle modificarOrdDet(Prototipo1.WSord.OrdenTrabajoDetalle ordDetModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/modificarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/modificarOrdDetResponse")]
        System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajoDetalle> modificarOrdDetAsync(Prototipo1.WSord.OrdenTrabajoDetalle ordDetModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/eliminarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/eliminarOrdDetResponse")]
        void eliminarOrdDet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/eliminarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/eliminarOrdDetResponse")]
        System.Threading.Tasks.Task eliminarOrdDetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/listarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/listarOrdDetResponse")]
        Prototipo1.WSord.OrdenTrabajoDetalle[] listarOrdDet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenTrabajoDetalle/listarOrdDet", ReplyAction="http://tempuri.org/IOrdenTrabajoDetalle/listarOrdDetResponse")]
        System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajoDetalle[]> listarOrdDetAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdenTrabajoDetalleChannel : Prototipo1.WSord.IOrdenTrabajoDetalle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenTrabajoDetalleClient : System.ServiceModel.ClientBase<Prototipo1.WSord.IOrdenTrabajoDetalle>, Prototipo1.WSord.IOrdenTrabajoDetalle {
        
        public OrdenTrabajoDetalleClient() {
        }
        
        public OrdenTrabajoDetalleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenTrabajoDetalleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajoDetalleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajoDetalleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Prototipo1.WSord.OrdenTrabajoDetalle crearOrdDet(Prototipo1.WSord.OrdenTrabajoDetalle ordDetCrear) {
            return base.Channel.crearOrdDet(ordDetCrear);
        }
        
        public System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajoDetalle> crearOrdDetAsync(Prototipo1.WSord.OrdenTrabajoDetalle ordDetCrear) {
            return base.Channel.crearOrdDetAsync(ordDetCrear);
        }
        
        public Prototipo1.WSord.OrdenTrabajoDetalle obtenerOrdDet(int id) {
            return base.Channel.obtenerOrdDet(id);
        }
        
        public System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajoDetalle> obtenerOrdDetAsync(int id) {
            return base.Channel.obtenerOrdDetAsync(id);
        }
        
        public Prototipo1.WSord.OrdenTrabajoDetalle modificarOrdDet(Prototipo1.WSord.OrdenTrabajoDetalle ordDetModificar) {
            return base.Channel.modificarOrdDet(ordDetModificar);
        }
        
        public System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajoDetalle> modificarOrdDetAsync(Prototipo1.WSord.OrdenTrabajoDetalle ordDetModificar) {
            return base.Channel.modificarOrdDetAsync(ordDetModificar);
        }
        
        public void eliminarOrdDet(int id) {
            base.Channel.eliminarOrdDet(id);
        }
        
        public System.Threading.Tasks.Task eliminarOrdDetAsync(int id) {
            return base.Channel.eliminarOrdDetAsync(id);
        }
        
        public Prototipo1.WSord.OrdenTrabajoDetalle[] listarOrdDet() {
            return base.Channel.listarOrdDet();
        }
        
        public System.Threading.Tasks.Task<Prototipo1.WSord.OrdenTrabajoDetalle[]> listarOrdDetAsync() {
            return base.Channel.listarOrdDetAsync();
        }
    }
}
